### ISSUE TITLE
Failed with multiple errors, see `details` for more information.

### ISSUE THREAD

**Issue by xiaoaozqd** [plantinformatics/pretzel-input-generator#31]
when i Uploaded the Oryza_sativa_IRGSP-1.0_VS_Triticum_urartu_Tu2.0_LC_aliases.json.gz, there is an error:"Oryza_sativa_IRGSP-1.0_VS_Triticum_urartu_Tu2.0_LC_aliases.json.gz", the details :
`details: Array(167) [ {…}, {…}, {…}, … ]
​
message: "Failed with multiple errors, see `details` for more information."
​
name: "ArrayOfErrors"
​
statusCode: 500
`

http://note.youdao.com/noteshare?id=5122bff3b7eba8b8ab0c80a92ab3f980&sub=A20FEBBEDEA84AEBADE6018900378502

**Comment by rsuchecki** [comment]
Please note that `*_aliases.json.gz` cannot be uploaded via the we interface, please follow the [data upload instructions](
https://github.com/plantinformatics/pretzel-input-generator/blob/master/doc/upload.md#data-upload-instructions)

**Comment by xiaoaozqd** [comment]
Thank you very much rsuchecki.
It worked.
while how can I generate the aliase file localy with two geneome files and gff files (or protein files)?

**Comment by rsuchecki** [comment]
closing as last comment raised as a separate issue
