### ISSUE TITLE
How to generate the aliase file with local files?

### ISSUE THREAD

**Issue by xiaoaozqd** [plantinformatics/pretzel-input-generator#32]
Thank you for this good tool!
I have no idea how to generate the aliase file with local files? We have improved one genome and want to compare and display the different between the new version and the old version. Which files should we prepare, such as two version's genome fasta file, protein files, gff files……？ How to generate the aliase files?

**Comment by rsuchecki** [comment]
First of all, an alias, in its simplest form is just a declaration that 2 features should be connected together, e.g.

```
    {
        "namespace1": "Arabidopsis_thaliana_TAIR10:Arabidopsis_thaliana_TAIR10_annotation",
        "namespace2": "Brachypodium_distachyon_v1.0:Brachypodium_distachyon_v1.0_annotation",
        "string1": "AT4G17150",
        "string2": "BRADI1G36220"
    },
```

These can be generate by the pipeline and I will try to update the documentation to make it clearer.

However, for  some uses, such as comparing two versions of a genome, it is usually better to rely on pretzel connecting two features based on their names e.g. the same marker is placed on each of the two assemblies or a gene prediction from version 1 is placed on version 2 of the assembly. This can also be done using the pipeline or one of the auxiliary scripts.

Would you be able to give me a little more information about your assemblies and what data you already have for them?

**Comment by xiaoaozqd** [comment]
Thank you very much for your advice!
For the old version, there are genome sequences, protein sequence and gff file.
For the new version, we only have genome sequences, we want to carry out the annotation to generate the protein and gff file based on the follow pipeline:
1.1 homology-based prediction based on V1 protein sequences
1.2 de novo prediction: August and Fgenesh+
1.3 transcriptome-based prediction based on published RNA-seq data.

**Comment by rsuchecki** [comment]
That's good, at this stage, given that these are different assemblies of the same organism 1.2 & 1.3 should not be required for comparing the assemblies in pretzel.  

From V1, given genome sequences and the gff, you could extract either

A. genomic sequences for each gene (including introns) 
B. transcript sequences
C. CDS 

(A) would be most specific, but itranscripts/CDS these should be fine as well.

- [x] I am updating the README and will be adding additional examples which should make running the pipeline with such inputs easier. In the meantime you could check if you are able to run the pipeline with the small test input data 

~https://github.com/plantinformatics/pretzel-input-generator#quick-start-example-using-yeast-data~

In addition to README, please refer to `conf/microsporidia.config` and `conf/test-data.config` to see how input data sets are defined - there is no longer any distinction between local and remote data sets, local files are used directly, remote ones are downloaded automatically before processing.

**Comment by rsuchecki** [comment]
I believe that information now available in the README and `conf/microsporidia.config, conf/test-data.config` should be sufficient for others to setup their inputs for generating aliases. 

Feel free to comment or re-open if you require further assistance @xiaoaozqd
